# Generated by Django 5.2.1 on 2025-05-31 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_code'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='타입명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='색상')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '컨텐츠 타입',
                'verbose_name_plural': '컨텐츠 타입',
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['subject', 'chapter_order'], 'verbose_name': '대단원', 'verbose_name_plural': '대단원'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': '코스', 'verbose_name_plural': '코스'},
        ),
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'ordering': ['-assigned_date'], 'verbose_name': '코스 할당', 'verbose_name_plural': '코스 할당'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_order',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='teacher.course', verbose_name='코스'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='할당일'),
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('page', models.TextField(verbose_name='내용')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='태그')),
                ('difficulty_level', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도')),
                ('estimated_time', models.PositiveIntegerField(default=5, verbose_name='예상 소요시간(분)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_contents', to='accounts.teacher', verbose_name='작성자')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.contenttype', verbose_name='컨텐츠 타입')),
            ],
            options={
                'verbose_name': '컨텐츠',
                'verbose_name_plural': '컨텐츠',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentsAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contents/attachments/%Y/%m/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='teacher.contents', verbose_name='컨텐츠')),
            ],
            options={
                'verbose_name': '컨텐츠 첨부파일',
                'verbose_name_plural': '컨텐츠 첨부파일',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_chapter_title', models.CharField(max_length=200, verbose_name='소단원명')),
                ('sub_chapter_order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='teacher.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course', verbose_name='코스')),
            ],
            options={
                'verbose_name': '소단원',
                'verbose_name_plural': '소단원',
                'ordering': ['chapter', 'sub_chapter_order'],
                'unique_together': {('chapter', 'sub_chapter_order')},
            },
        ),
        migrations.CreateModel(
            name='Chasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasi_title', models.CharField(max_length=200, verbose_name='차시명')),
                ('chasi_order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('chapter_order', models.PositiveIntegerField(default=1, verbose_name='대단원 순서')),
                ('sub_chapter_order', models.PositiveIntegerField(default=1, verbose_name='소단원 순서')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='학습목표')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='수업시간(분)')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course', verbose_name='코스')),
                ('sub_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasis', to='teacher.subchapter', verbose_name='소단원')),
            ],
            options={
                'verbose_name': '차시',
                'verbose_name_plural': '차시',
                'ordering': ['sub_chapter', 'chasi_order'],
                'unique_together': {('sub_chapter', 'chasi_order')},
            },
        ),
        migrations.CreateModel(
            name='ChasiSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField(verbose_name='슬라이드 번호')),
                ('slide_title', models.CharField(blank=True, max_length=200, verbose_name='슬라이드 제목')),
                ('instructor_notes', models.TextField(blank=True, verbose_name='강사 노트')),
                ('estimated_time', models.PositiveIntegerField(default=5, verbose_name='예상 시간(분)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('chasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_slides', to='teacher.chasi', verbose_name='차시')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.contents', verbose_name='컨텐츠')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.contenttype', verbose_name='컨텐츠 타입')),
            ],
            options={
                'verbose_name': '차시 슬라이드',
                'verbose_name_plural': '차시 슬라이드',
                'ordering': ['chasi', 'slide_number'],
                'unique_together': {('chasi', 'slide_number')},
            },
        ),
    ]
