# Generated by Django 5.2.1 on 2025-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_contenttype_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='difficulty_level',
            field=models.CharField(choices=[('basic', '기초'), ('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움'), ('ultra', '초고난도')], default='medium', max_length=10, verbose_name='난이도'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='tags',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='메타데이터'),
        ),
    ]
