# Generated by Django 5.2.1 on 2025-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_contents_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='is_public',
            field=models.BooleanField(default=False, help_text='다른 교사들도 사용할 수 있도록 공개', verbose_name='공개'),
        ),
    ]
