# Generated by Django 5.2.1 on 2025-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_contents_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='아이콘'),
        ),
    ]
