# Generated by Django 5.2.1 on 2025-06-03 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_code'),
        ('teacher', '0006_alter_contenttype_color_alter_contenttype_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'verbose_name': '코스 할당', 'verbose_name_plural': '코스 할당'},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'assigned_class'), ('course', 'assigned_student')},
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.class'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='assigned_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['course', 'assigned_class'], name='teacher_cou_course__ef6cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['course', 'assigned_student'], name='teacher_cou_course__3af126_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['due_date'], name='teacher_cou_due_dat_15aa9a_idx'),
        ),
        migrations.AlterModelTable(
            name='courseassignment',
            table='teacher_course_assignment',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='is_active',
        ),
    ]
