# Generated by Django 5.2.1 on 2025-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='is_public',
            field=models.BooleanField(default=True, help_text='다른 교사들도 사용할 수 있도록 공개', verbose_name='공개'),
        ),
    ]
