# Generated by Django 5.2.1 on 2025-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_contents_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chasi',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='공개'),
        ),
    ]
