# Generated by Django 5.2.1 on 2025-06-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_chasi_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
