# Generated by Django 5.2.1 on 2025-06-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_contents_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, null=True, verbose_name='카테고리 설명')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='아이콘')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='색상')),
            ],
            options={
                'verbose_name': '컨텐츠 카테고리',
                'verbose_name_plural': '컨텐츠 카테고리',
            },
        ),
        migrations.AddField(
            model_name='contenttype',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.contenttypecategory', verbose_name='콘텐츠 카테고리'),
        ),
    ]
