# Generated by Django 5.2.1 on 2025-06-28 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_contenttypecategory_contenttype_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsattached',
            name='is_temporary',
            field=models.BooleanField(default=True, help_text='임시 업로드 파일인지 여부', verbose_name='임시 파일'),
        ),
        migrations.AddField(
            model_name='contentsattached',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자'),
        ),
        migrations.AlterField(
            model_name='contentsattached',
            name='contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='teacher.contents', verbose_name='컨텐츠'),
        ),
        migrations.AddIndex(
            model_name='contentsattached',
            index=models.Index(fields=['contents', 'uploaded_at'], name='teacher_con_content_5e01f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsattached',
            index=models.Index(fields=['is_temporary', 'uploaded_at'], name='teacher_con_is_temp_0f17d1_idx'),
        ),
    ]
