# Generated by Django 5.2.1 on 2025-05-30 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='대단원명')),
                ('chapter_order', models.IntegerField(verbose_name='대단원 순서')),
            ],
            options={
                'verbose_name': '대단원',
                'verbose_name_plural': '대단원들',
                'ordering': ['chapter_order'],
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('page', models.TextField(verbose_name='페이지 내용(HTML)')),
                ('meta_data', models.JSONField(default=dict, verbose_name='메타데이터(루브릭)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '컨텐츠',
                'verbose_name_plural': '컨텐츠들',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='타입명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '컨텐츠 타입',
                'verbose_name_plural': '컨텐츠 타입들',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='과목명')),
                ('target', models.CharField(max_length=100, verbose_name='대상')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '코스',
                'verbose_name_plural': '코스들',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학교명')),
                ('address', models.TextField(verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교들',
            },
        ),
        migrations.CreateModel(
            name='Chasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(verbose_name='대단원 순서')),
                ('sub_chapter_order', models.IntegerField(verbose_name='소단원 순서')),
                ('chasi_title', models.CharField(max_length=200, verbose_name='차시명')),
                ('chasi_order', models.IntegerField(verbose_name='차시 순서')),
                ('description', models.TextField(blank=True, verbose_name='차시 설명')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.course', verbose_name='과목')),
            ],
            options={
                'verbose_name': '차시',
                'verbose_name_plural': '차시들',
                'ordering': ['chasi_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentsAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contents_files/', verbose_name='파일')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('original_name', models.CharField(max_length=200, verbose_name='원본 파일명')),
                ('file_size', models.IntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.contents', verbose_name='컨텐츠')),
            ],
            options={
                'verbose_name': '컨텐츠 첨부파일',
                'verbose_name_plural': '컨텐츠 첨부파일들',
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.contenttype', verbose_name='컨텐츠 타입'),
        ),
        migrations.CreateModel(
            name='ChasiSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(verbose_name='슬라이드 번호')),
                ('chasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chasi', verbose_name='차시')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.contents', verbose_name='컨텐츠')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.contenttype', verbose_name='컨텐츠 타입')),
            ],
            options={
                'verbose_name': '차시 슬라이드',
                'verbose_name_plural': '차시 슬라이드들',
                'ordering': ['slide_number'],
                'unique_together': {('chasi', 'slide_number')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.course', verbose_name='과목'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('class_number', models.IntegerField(verbose_name='반')),
                ('name', models.CharField(max_length=50, verbose_name='학급명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.school')),
            ],
            options={
                'verbose_name': '학급',
                'verbose_name_plural': '학급들',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='학번')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.class', verbose_name='학급')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생들',
                'unique_together': {('school_class', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.class', verbose_name='할당 학급')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.course', verbose_name='코스')),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.student', verbose_name='할당 학생')),
            ],
            options={
                'verbose_name': '코스 할당',
                'verbose_name_plural': '코스 할당들',
            },
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_chapter_title', models.CharField(max_length=200, verbose_name='소단원명')),
                ('sub_chapter_order', models.IntegerField(verbose_name='소단원 순서')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.course', verbose_name='과목')),
            ],
            options={
                'verbose_name': '소단원',
                'verbose_name_plural': '소단원들',
                'ordering': ['sub_chapter_order'],
                'unique_together': {('chapter', 'sub_chapter_order')},
            },
        ),
        migrations.AddField(
            model_name='chasi',
            name='sub_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.subchapter', verbose_name='소단원'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='사번')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '교사',
                'verbose_name_plural': '교사들',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.teacher', verbose_name='담당교사'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.teacher', verbose_name='담당교사'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_order')},
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(default=dict, verbose_name='답안 데이터')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='정답 여부')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수')),
                ('feedback', models.TextField(blank=True, verbose_name='피드백')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 답안',
                'verbose_name_plural': '학생 답안들',
                'unique_together': {('student', 'slide')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('chasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chasi', verbose_name='차시')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 진행 상황',
                'verbose_name_plural': '학생 진행 상황들',
                'unique_together': {('student', 'slide')},
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(default=1, verbose_name='회차')),
                ('record_data', models.JSONField(default=dict, verbose_name='기록 데이터')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 수행 기록',
                'verbose_name_plural': '학생 수행 기록들',
                'unique_together': {('student', 'slide', 'session_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chasi',
            unique_together={('sub_chapter', 'chasi_order')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'grade', 'class_number')},
        ),
    ]
