# Generated by Django 5.2.1 on 2025-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='SC001', max_length=10, unique=True),
        ),
    ]
