# Generated by Django 5.2.1 on 2025-06-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_school_code'),
        ('teacher', '0002_contenttype_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(default=dict, verbose_name='답안 데이터')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='정답 여부')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수')),
                ('feedback', models.TextField(blank=True, verbose_name='피드백')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 답안',
                'verbose_name_plural': '학생 답안들',
                'unique_together': {('student', 'slide')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 진행 상황',
                'verbose_name_plural': '학생 진행 상황들',
                'unique_together': {('student', 'slide')},
            },
        ),
    ]
