# Generated by Django 5.2.1 on 2025-06-02 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_code'),
        ('student', '0001_initial'),
        ('teacher', '0006_alter_contenttype_color_alter_contenttype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='노트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 노트',
                'verbose_name_plural': '학생 노트 목록',
                'unique_together': {('student', 'slide')},
            },
        ),
    ]
