# Generated by Django 5.2.1 on 2025-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['-submitted_at'], 'verbose_name': '학생 답안', 'verbose_name_plural': '학생 답안들'},
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='answer_data',
            new_name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
