# Generated by Django 5.2.1 on 2025-06-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_code'),
        ('student', '0003_alter_studentanswer_options_and_more'),
        ('teacher', '0008_alter_contents_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'slide')},
        ),
    ]
