# Generated by Django 5.2.1 on 2025-06-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_code'),
        ('student', '0004_alter_studentanswer_submitted_at_and_more'),
        ('teacher', '0008_alter_contents_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=100, null=True)),
                ('type_name', models.CharField(default='달리기', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '기록 유형',
                'verbose_name_plural': '기록 유형 목록',
                'unique_together': {('type_code', 'type_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentPhysicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FloatField(default=0)),
                ('writer', models.CharField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='발생일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chasislide', verbose_name='슬라이드')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 기록',
                'verbose_name_plural': '학생 기록들',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'slide')},
            },
        ),
    ]
