# Generated by Django 5.2.1 on 2025-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_physicalresulttype_studentphysicalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalresulttype',
            name='measure',
            field=models.CharField(default='mili_second', max_length=100),
        ),
    ]
