# Generated by Django 5.2.1 on 2025-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_physicalresulttype_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphysicalresult',
            name='record',
            field=models.JSONField(default=dict, verbose_name='기록결과'),
        ),
    ]
