# Generated by Django 5.2.1 on 2025-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentphysicalresult_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphysicalresult',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
