# Generated by Django 5.2.1 on 2025-06-15 20:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_class_teacher_classteacher_class_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('is_success_category', models.BooleanField()),
                ('keywords', models.TextField(help_text='쉼표로 구분된 키워드')),
            ],
            options={
                'verbose_name': '피드백 카테고리',
                'verbose_name_plural': '피드백 카테고리들',
            },
        ),
        migrations.CreateModel(
            name='RollingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', '🏆 최우수'), ('B', '🥇 우수'), ('C', '🥈 보통'), ('D', '🥉 노력 필요')], max_length=1, verbose_name='등급')),
                ('overall_feedback', models.TextField(verbose_name='종합 피드백')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='평가일')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rolling_evaluation', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'verbose_name': '앞구르기 종합 평가',
                'verbose_name_plural': '앞구르기 종합 평가들',
            },
        ),
        migrations.CreateModel(
            name='RollingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_success', models.BooleanField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolling_attempts', to='accounts.student')),
            ],
            options={
                'verbose_name': '앞구르기 시도',
                'verbose_name_plural': '앞구르기 시도들',
                'ordering': ['attempt_number'],
                'unique_together': {('student', 'attempt_number')},
            },
        ),
    ]
