# Generated by Django 5.2.1 on 2025-06-25 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_class_teacher_classteacher_class_teachers'),
        ('teacher', '0011_contenttypecategory_contenttype_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCSCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='역량코드')),
                ('main_category', models.CharField(max_length=100, verbose_name='대분류')),
                ('sub_category', models.CharField(max_length=100, verbose_name='중분류')),
                ('competency_name', models.CharField(max_length=200, verbose_name='역량명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('level', models.IntegerField(default=1, verbose_name='레벨')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ncs.ncscompetency')),
            ],
            options={
                'verbose_name': 'NCS 역량',
                'verbose_name_plural': 'NCS 역량',
                'ordering': ['level', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NCSAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='과제명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('assignment_type', models.CharField(choices=[('individual', '개인별'), ('class', '반별'), ('weakness', '취약점 보강')], max_length=20, verbose_name='할당 타입')),
                ('question_count', models.IntegerField(default=10, verbose_name='문항 수')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.class', verbose_name='할당 반')),
                ('assigned_students', models.ManyToManyField(blank=True, to='accounts.student', verbose_name='할당 학생')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='교사')),
                ('competencies', models.ManyToManyField(to='ncs.ncscompetency', verbose_name='대상 역량')),
            ],
            options={
                'verbose_name': 'NCS 과제',
                'verbose_name_plural': 'NCS 과제',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NCSLearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('auto', '자동 추천'), ('manual', '수동 선택'), ('weakness', '취약점 보강')], max_length=20, verbose_name='세션 타입')),
                ('total_questions', models.IntegerField(default=0, verbose_name='총 문항 수')),
                ('completed_questions', models.IntegerField(default=0, verbose_name='완료 문항 수')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='정답 수')),
                ('score', models.FloatField(default=0.0, verbose_name='점수')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('time_spent', models.IntegerField(default=0, verbose_name='소요 시간(초)')),
                ('competencies', models.ManyToManyField(to='ncs.ncscompetency', verbose_name='대상 역량')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': 'NCS 학습 세션',
                'verbose_name_plural': 'NCS 학습 세션',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NCSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변 여부')),
                ('student_answer', models.CharField(blank=True, max_length=10, verbose_name='학생 답안')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='정답 여부')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변 시간')),
                ('time_spent', models.IntegerField(default=0, verbose_name='소요 시간(초)')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncs.ncscompetency', verbose_name='역량')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.contents', verbose_name='콘텐츠')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ncs.ncslearningsession')),
            ],
            options={
                'verbose_name': 'NCS 학습 문항',
                'verbose_name_plural': 'NCS 학습 문항',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NCSClassStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_accuracy', models.FloatField(default=0.0, verbose_name='평균 정답률')),
                ('total_students', models.IntegerField(default=0, verbose_name='전체 학생 수')),
                ('participated_students', models.IntegerField(default=0, verbose_name='참여 학생 수')),
                ('average_attempts', models.FloatField(default=0.0, verbose_name='평균 시도 횟수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.class', verbose_name='반')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncs.ncscompetency', verbose_name='역량')),
            ],
            options={
                'verbose_name': '반별 NCS 통계',
                'verbose_name_plural': '반별 NCS 통계',
                'unique_together': {('class_obj', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='NCSCompetencyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='총 시도 횟수')),
                ('correct_count', models.IntegerField(default=0, verbose_name='정답 횟수')),
                ('incorrect_count', models.IntegerField(default=0, verbose_name='오답 횟수')),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='정답률')),
                ('average_time', models.FloatField(default=0.0, verbose_name='평균 소요 시간(초)')),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 시도일')),
                ('weakness_score', models.FloatField(default=0.0, verbose_name='취약도 점수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncs.ncscompetency', verbose_name='역량')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': 'NCS 역량 분석',
                'verbose_name_plural': 'NCS 역량 분석',
                'ordering': ['-weakness_score', 'competency__code'],
                'unique_together': {('student', 'competency')},
            },
        ),
    ]
