# Generated by Django 5.2.1 on 2025-06-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_class_teacher_classteacher_class_teachers'),
        ('ncs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncsquestion',
            name='current_attempt_count',
            field=models.IntegerField(default=0, verbose_name='현재 시도 횟수'),
        ),
        migrations.AddField(
            model_name='ncsquestion',
            name='max_attempts',
            field=models.IntegerField(default=3, verbose_name='최대 시도 횟수'),
        ),
        migrations.CreateModel(
            name='NCSQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='시도 번호')),
                ('answer', models.CharField(max_length=10, verbose_name='답안')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='시도 시간')),
                ('time_spent', models.IntegerField(default=0, verbose_name='소요 시간(초)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ncs.ncsquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': 'NCS 문항 시도',
                'verbose_name_plural': 'NCS 문항 시도',
                'ordering': ['question', 'attempt_number'],
                'unique_together': {('question', 'student', 'attempt_number')},
            },
        ),
    ]
