# Generated by Django 5.2.1 on 2025-06-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncs', '0002_ncsquestion_current_attempt_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCSStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10, verbose_name='답안')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('attempt_count', models.IntegerField(default=1, verbose_name='시도 횟수')),
                ('time_spent', models.IntegerField(default=0, verbose_name='소요 시간(초)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시간')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ncs.ncsquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='ncs.ncslearningsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCS 학생 답안',
                'verbose_name_plural': 'NCS 학생 답안',
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'question', 'student')},
            },
        ),
    ]
