# Generated by Django 5.2.1 on 2025-05-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('page', models.TextField(verbose_name='페이지 내용(HTML)')),
                ('meta_data', models.JSONField(default=dict, verbose_name='메타데이터(루브릭)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '컨텐츠',
                'verbose_name_plural': '컨텐츠들',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='타입명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '컨텐츠 타입',
                'verbose_name_plural': '컨텐츠 타입들',
            },
        ),
        migrations.CreateModel(
            name='ContentsAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contents_files/', verbose_name='파일')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('original_name', models.CharField(max_length=200, verbose_name='원본 파일명')),
                ('file_size', models.IntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.contents', verbose_name='컨텐츠')),
            ],
            options={
                'verbose_name': '컨텐츠 첨부파일',
                'verbose_name_plural': '컨텐츠 첨부파일들',
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.contenttype', verbose_name='컨텐츠 타입'),
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_chapter_title', models.CharField(max_length=200, verbose_name='소단원명')),
                ('sub_chapter_order', models.IntegerField(verbose_name='소단원 순서')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course', verbose_name='과목')),
            ],
            options={
                'verbose_name': '소단원',
                'verbose_name_plural': '소단원들',
                'ordering': ['sub_chapter_order'],
                'unique_together': {('chapter', 'sub_chapter_order')},
            },
        ),
        migrations.CreateModel(
            name='Chasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(verbose_name='대단원 순서')),
                ('sub_chapter_order', models.IntegerField(verbose_name='소단원 순서')),
                ('chasi_title', models.CharField(max_length=200, verbose_name='차시명')),
                ('chasi_order', models.IntegerField(verbose_name='차시 순서')),
                ('description', models.TextField(blank=True, verbose_name='차시 설명')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.chapter', verbose_name='대단원')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course', verbose_name='과목')),
                ('sub_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.subchapter', verbose_name='소단원')),
            ],
            options={
                'verbose_name': '차시',
                'verbose_name_plural': '차시들',
                'ordering': ['chasi_order'],
                'unique_together': {('sub_chapter', 'chasi_order')},
            },
        ),
        migrations.CreateModel(
            name='ChasiSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(verbose_name='슬라이드 번호')),
                ('chasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.chasi', verbose_name='차시')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.contents', verbose_name='컨텐츠')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.contenttype', verbose_name='컨텐츠 타입')),
            ],
            options={
                'verbose_name': '차시 슬라이드',
                'verbose_name_plural': '차시 슬라이드들',
                'ordering': ['slide_number'],
                'unique_together': {('chasi', 'slide_number')},
            },
        ),
    ]
